import Link from "next/link";
import Image from "next/image";
import { Reveal } from "@/components/Reveal";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { QuickCheckPanel } from "@/components/QuickCheckPanel";
import { faqs, features, problems } from "@/content/lp";

export default function Home() {
  const structuredData={"@context":"https://schema.org","@type":"Service",name:"Lance Up",serviceType:"ITエンジニア向けフリーランス相談",description:"ITエンジニアの経験と希望を確認し、必要に応じて提携エージェントの代表・責任者クラスへつなぐ無料相談サービス",areaServed:{"@type":"Country",name:"Japan"},audience:{"@type":"Audience",audienceType:"ITエンジニア"},offers:{"@type":"Offer",price:"0",priceCurrency:"JPY"},url:process.env.NEXT_PUBLIC_SITE_URL||"https://lanceup.jp"};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><SiteHeader/><main>
    <section className="hero"><div className="container">
      <div className="hero-grid">
        <div className="hero-copy"><p className="audience-label">フリーランスを検討するITエンジニアの方へ</p><h1><span className="hero-line hero-main-line">今の経験で、<strong>フリーランスとして</strong></span><span className="hero-line"><span className="hero-question-part">通用するか</span><span className="hero-question-part">確認しませんか？</span></span></h1><p className="lead">会社を辞める前でも相談できます。経験と現在の状況を入力して、次の選択肢を考えるきっかけに。</p><div className="hero-action"><Link href="/check" className="btn btn-primary hero-cta"><span>無料でチェックする</span><span className="cta-arrow" aria-hidden="true">→</span></Link><small>入力は約1分・相談無料</small></div><div className="hero-note"><span>会社員のまま相談OK</span><span>独立するか未定でもOK</span></div></div>
        <div className="hero-visual" aria-hidden="true"><Image src="/images/hero-engineer-companion.png" alt="" width={1024} height={1536} priority sizes="(min-width: 1180px) 340px, 0px"/></div>
        <div className="signal" aria-label="無料チェックからご連絡まで"><div className="signal-accent">経歴を確認後、直接ご紹介</div><div className="signal-top"><p>このサービスなら</p><h2>一般窓口ではなく、<br/><em>代表・責任者クラスへ直接</em></h2></div><div className="signal-list"><div className="signal-item"><span className="check-icon">✓</span><div><b>経験・スキルを確認</b><br/><small className="muted">実務年数と主な技術を整理</small></div></div><div className="signal-item"><span className="check-icon">✓</span><div><b>現在の状況を確認</b><br/><small className="muted">働き方と検討時期を確認</small></div></div><div className="signal-item"><span className="check-icon">→</span><div><b>責任者クラスへ直接接続</b><br/><small className="muted">提携エージェントへスムーズに接続</small></div></div></div></div>
      </div>
      <div className="direct-access" aria-labelledby="direct-title"><div className="strength-badge">このサービス最大の強み</div><div className="direct-heading"><span className="direct-access-mark" aria-hidden="true">直接</span><div><p>相談のスタート地点が違います</p><h2 id="direct-title">経歴を確認後、提携エージェントの<br className="desktop-only"/>代表・責任者クラスへ直接つなげます</h2></div></div><div className="route-compare"><div className="route-card route-standard"><span className="route-label">一般的な相談ルート</span><div className="route-path"><span className="route-node">相談を申し込む</span><span className="route-arrow">→</span><strong>通常の問い合わせ窓口</strong></div></div><div className="route-divider" aria-hidden="true">／</div><div className="route-card route-featured"><span className="route-label">このサービス</span><div className="route-path"><span className="route-node">経歴を確認</span><span className="route-arrow">→</span><span className="route-node">提携先を検討</span><span className="route-arrow">→</span><strong>代表・責任者クラス</strong></div></div></div><div className="direct-footer"><p><strong>一般窓口を経由せず、意思決定に近い方へ。</strong><br/>経歴や状況に応じて、スムーズな相談につながる入口をつくります。</p><Link href="/check" className="direct-link">無料チェックへ <span aria-hidden="true">→</span></Link></div></div>
    </div></section>

    <section className="section problems"><Reveal className="container"><div className="section-heading"><span>よくある悩み</span><h2 className="title">こんな迷いはありませんか？</h2></div><div className="problem-grid">{problems.map((item)=><article className="card problem" key={item.title}><span className="problem-icon" aria-hidden="true">?</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></Reveal></section>
    <section className="section service" id="features"><Reveal className="container"><div className="section-heading"><span>サービスの特徴</span><h2 className="title">まずは、今の経験と希望を整理するところから</h2></div><p className="lead">すぐに独立を決める必要はありません。入力内容を確認し、これからの相談の進め方を考えます。</p><div className="grid3 feature-grid">{features.map((item)=><article className="card feature" key={item.title}><span className="feature-check">✓</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="partner-highlight card"><div><span className="partner-label">このサービスの特徴</span><h3>複数の提携先を検討し、代表・責任者クラスへ直接</h3></div><p>エンジニアの経験や検討時期は一人ひとり異なります。経歴を確認し、状況に合いそうな提携エージェントを検討したうえで、一般窓口ではなく代表・責任者クラスへ直接つなげます。</p></div></Reveal></section>
    <section className="section support-section" id="support"><Reveal className="container"><div className="support-intro"><div><span className="support-kicker">相談から次の一歩まで</span><h2 className="title">無料チェック後も、次の一歩までサポート</h2><p>経験の整理から相談先への接続まで、無理のないペースで進めます。</p></div><div className="support-promise"><strong>NO PRESSURE</strong><span>しつこい勧誘・催促はありません。相談したからといって、独立や契約を急かすこともありません。</span></div></div><div className="support-grid"><article><span>01</span><h3>経験・スキルシートの整理</h3><p>経験や希望条件の整理に加え、必要に応じてスキルシートの作成・見直しもお手伝いします。</p></article><article><span>02</span><h3>相談先の検討</h3><p>複数の提携先から、状況に合いそうなエージェントを検討します。</p></article><article><span>03</span><h3>責任者へ接続</h3><p>提携エージェントの代表・責任者クラスへ直接つなぎ、相談開始を支援します。</p></article><article className="tax-support"><span>＋</span><h3>税金・確定申告の相談先も</h3><p>必要に応じて、FPや税理士へ相談できる体制を持つ提携エージェントをご案内できる場合があります。</p></article></div><div className="support-flow"><div className="support-flow-title"><span>ご利用の流れ</span><strong>約1分の入力から始められます</strong></div>{[["01","無料チェック","経験や現在の状況を入力"],["02","内容を確認","いただいた内容を確認"],["03","ご連絡","確認後、メール等でご連絡"]].map(([number,title,text])=><article key={number}><b>{number}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></Reveal></section>
    <section className="section audience-section"><Reveal className="container audience"><div><h2 className="title">独立するか決めていない方も、活動中の方も</h2><p className="lead">現役ITエンジニアを対象とした、フリーランス相談が中心のサービスです。</p><div className="notice"><b>外国籍の方もご相談いただけます。</b><br/>日本語での業務・面談対応が必要です。</div></div><ul className="checklist"><li>フリーランスを検討中の会社員</li><li>将来に向けて情報収集したい方</li><li>すでにフリーランスとして活動中の方</li><li>希望条件や相談先を整理したい方</li></ul></Reveal></section>
    <section className="section stories-section" id="stories"><Reveal className="container"><div className="section-heading light"><span>リアルな経験から</span><h2 className="title">体験談</h2><p>数字だけでは伝わらない、独立を考えたときの迷いや相談後の変化をお伝えします。</p></div><div className="story-grid"><article className="story-card owner-story"><div className="story-speaker"><span className="story-avatar owner-avatar"><Image src="/images/testimonial-characters.png" alt="運営者のイラスト" width={1696} height={881} sizes="112px"/></span><div><div className="story-type">運営者の実体験</div><h3>私も、「この経験で独立できるのか」と悩んでいました</h3></div></div><div className="story-body"><p>私は26歳で塾講師からIT業界へ転職しました。未経験に近い状態から実務経験を積みましたが、仕事の幅が広がっても待遇がなかなか変わらず不安がありました。</p><p>はじめはフリーランスという発想もなく、仕事の見つけ方もわかりませんでした。</p><p>友人にフリーランスの話を聞き、「給料が上がるなら」という理由で転向しました。</p><p>実際に独立して感じたのは、自分の経歴を理解してくれる相談相手と出会うことの大切さです。</p><p>その思いから、このサービスでは一般窓口ではなく、提携エージェントの代表・責任者クラスへ直接つなぐことを大切にしています。</p><p>まだ会社を辞める必要はありません。私自身の経験も交えながら、まずは今の状況を一緒に整理します。</p></div></article><article className="story-card user-story"><div className="story-speaker"><span className="story-avatar user-avatar"><Image src="/images/testimonial-characters.png" alt="利用者のイラスト" width={1696} height={881} sizes="112px"/></span><div><div className="story-type">利用者の体験談</div><h3>転職や独立を急かされず、今後の選択肢を整理できました</h3></div></div><div className="story-body"><p>フリーランスには興味がありましたが、自分の経験で通用するのか分からず、すぐに会社を辞めるつもりもありませんでした。</p><p>相談して良かったのは、これまでの経験や希望を落ち着いて整理できたことです。運営者の方にも会社員から独立した経験があるため、収入面だけでなく、仕事を変える不安やスキルシート、税金、確定申告についても相談できました。</p><p>経歴を確認したうえで、話の早い責任者クラスへつないでもらえる点もよかったです。</p><p>案件を紹介されるだけの関係ではなく、丁寧なやり取りをしていただけたのでとても助かりました。</p></div></article></div></Reveal></section>
    <section className="section faq-section" id="faq"><Reveal className="container faq"><div className="section-heading"><span>疑問を解消</span><h2 className="title">よくある質問</h2></div>{faqs.map((item)=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</Reveal></section>
    <section className="cta-section"><Reveal className="container"><div className="final-cta"><h2 className="title">会社を辞める前に、まずは経験を整理。</h2><p>フリーランスという選択肢を、無料で確認してみませんか？</p><Link className="btn btn-primary" href="/check">無料でチェックする</Link></div></Reveal></section>
  </main><QuickCheckPanel/><SiteFooter/></>;
}
