import { fireEvent, render, screen } from "@testing-library/react";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { ContactForm } from "./ContactForm";

vi.mock("next/navigation",()=>({useRouter:()=>({push:vi.fn()})}));
beforeAll(()=>{Object.defineProperty(globalThis.crypto,"randomUUID",{value:()=>"550e8400-e29b-41d4-a716-446655440000"});Object.defineProperty(window,"scrollTo",{value:vi.fn()});});
describe("ContactForm",()=>{
  it("does not count the start screen, then opens step one",()=>{render(<ContactForm/>);expect(screen.queryByText(/ステップ 1/)).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"無料チェックを始める"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"無料チェックを始める"}));expect(screen.getByText("ステップ 1 / 3")).toBeInTheDocument();expect(screen.getByText("33%")).toBeInTheDocument();expect(screen.getByText("経験と現在の状況")).toBeInTheDocument();expect(screen.getByLabelText(/IT実務経験年数/)).toBeInTheDocument();expect(screen.getByLabelText(/現在の雇用形態/)).toBeInTheDocument();expect(screen.queryByLabelText("職種")).not.toBeInTheDocument();});
  it("retains optional technologies after navigating back",()=>{render(<ContactForm/>);fireEvent.click(screen.getByRole("button",{name:"無料チェックを始める"}));fireEvent.change(screen.getByLabelText(/IT実務経験年数/),{target:{value:"3〜5年"}});fireEvent.change(screen.getByLabelText(/主な使用技術/),{target:{value:"React"}});fireEvent.change(screen.getByLabelText(/現在の雇用形態/),{target:{value:"正社員"}});fireEvent.change(screen.getByLabelText(/フリーランスへの関心/),{target:{value:"半年以内"}});fireEvent.click(screen.getByRole("button",{name:"次へ"}));expect(screen.getByText("ステップ 2 / 3")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"戻る"}));expect(screen.getByDisplayValue("React")).toBeInTheDocument();});
  it("shows one consent on step three and blocks submit without it",()=>{const fetchMock=vi.spyOn(globalThis,"fetch");render(<ContactForm/>);fireEvent.click(screen.getByRole("button",{name:"無料チェックを始める"}));fireEvent.change(screen.getByLabelText(/IT実務経験年数/),{target:{value:"3〜5年"}});fireEvent.change(screen.getByLabelText(/現在の雇用形態/),{target:{value:"正社員"}});fireEvent.change(screen.getByLabelText(/フリーランスへの関心/),{target:{value:"半年以内"}});fireEvent.click(screen.getByRole("button",{name:"次へ"}));fireEvent.change(screen.getByLabelText(/氏名/),{target:{value:"山田 太郎"}});fireEvent.change(screen.getByLabelText(/お住まいの都道府県/),{target:{value:"東京都"}});fireEvent.change(screen.getByLabelText(/年齢/),{target:{value:"32"}});fireEvent.click(screen.getByRole("button",{name:"次へ"}));expect(screen.getByText("ステップ 3 / 3")).toBeInTheDocument();expect(screen.getByText("100%")).toBeInTheDocument();expect(screen.getAllByRole("checkbox")).toHaveLength(1);fireEvent.click(screen.getByRole("button",{name:"同意して送信する"}));expect(screen.getByRole("alert")).toHaveTextContent("同意が必要です");expect(fetchMock).not.toHaveBeenCalled();fetchMock.mockRestore();});
});
